
name: Build Plugin for deployment

concurrency: build-plugin

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: build-plugin

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          coverage: none
          tools: composer, cs2pr

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: NodeJS Dev cache
        id: node-dev-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-dev-${{ hashFiles( 'package-lock.json' ) }}-${{ hashFiles( '.github/workflows/build-plugin.yml' ) }}

      - name: Install NodeJS dependencies (with dev)
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build plugin
        run: npm run build:prod

      - name: Cleanup node node_modules
        run: rm -rf node_modules

      - name: NodeJS cache
        id: node-prod-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-prod-${{ hashFiles( 'package-lock.json' ) }}-${{ hashFiles( '.github/workflows/build-plugin.yml' ) }}

      - name: Install NodeJS dependencies (with dev)
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci --omit=dev

      - name: Cleanup
        run: bash bin/prepare.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: all-about-modal
          path: .
